In [1]:
pip install pandas

Requirement already satisfied: pandas in .\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in .\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in .\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in .\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
#series
a=[10,20,30,40,50]
pd.Series(a)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
b=[2.3,5.6]
pd.Series(b)

0    2.3
1    5.6
dtype: float64

In [5]:
c=["uma","mahi","ammu"]
pd.Series(c)

0     uma
1    mahi
2    ammu
dtype: str

In [6]:
d=[True,False]
pd.Series(d)

0     True
1    False
dtype: bool

In [7]:
e=[9+6j,2+6j,3+5j]
pd.Series(e)

0    9.0+6.0j
1    2.0+6.0j
2    3.0+5.0j
dtype: complex128

In [8]:
#dataframe
details={"names":["uma","mahi","ammu"],"marks":[70,80,90]}
pd.DataFrame(details)

  names  marks
0   uma     70
1  mahi     80
2  ammu     90

In [9]:
#names,subjects,marks,percentages
student_details={"names":["uma","mahi","ammu"],"subjects":["maths","science","telugu"],"marks":[70,80,90],"percenatages":[70,80,90]}
pd.DataFrame(student_details)

  names subjects  marks  percenatages
0   uma    maths     70            70
1  mahi  science     80            80
2  ammu   telugu     90            90

In [6]:
data=pd.read_csv("details.csv")
data

    names  subject
0     uma  english
1    rani    hindi
2   roopa   telugu
3  santhi  science
4    sana   social

In [8]:
import pandas as pd
data=pd.read_csv("key_pubmed.csv")
data

,title,doi,abstract,journal,date,authors,year,keyword
0,IV. Prolapsus of the Rectum in Children.,10.1097/00000658-190001000-00028,NaN,Annals of surgery,1900-03-01,['C GCumston'],1900.0,['hemorrhoids']
1,HEMIANOPSIA IN MIGRAINE.,10.1126/science.11.279.713-a,NaN,"Science (New York, N.Y.)",1900-05-04,['J MBaldwin'],1900.0,['migraine']
2,An attempt to estimate fatigue of the cerebral...,10.1113/jphysiol.1901.sp000832,NaN,The Journal of physiology,1901-02-28,['A GLevy'],1901.0,['fatigue']
3,VII. Report of a Case of Recovery after Abdomi...,10.1097/00000658-190101000-00030,NaN,Annals of surgery,1901-03-01,['FMartin'],1901.0,['hemorrhoids']
4,A further research into fatigue of the central...,10.1113/jphysiol.1902.sp000895,NaN,The Journal of physiology,1902-03-27,['A GLevy'],1902.0,['fatigue']
...,...,...,...,...,...,...,...,...
2235181,Serotonin Degradation and Lipid Metabolism Reg...,10.1111/all.70399,Cytotoxic type 2 T cells (Tc2) are increasingl...,Allergy,2026-07-01,"['Sabrinade Souza Ferreira', 'LisaHolla', 'Sop...",2026.0,['allergic']
2235182,Investigating the Potential Pharmacological Me...,10.2174/0113862073449045260321213418,Allergic rhinitis (AR) is a common immune diso...,Combinatorial chemistry & high throughput scre...,2026-07-01,"['ZehuaLin', 'AikebaierTuohuti', 'XiupingYang'...",2026.0,['allergic']
2235183,Bridging environmental pollution and immune dy...,10.1080/21505594.2026.2690759,Parallel increases in microplastic (MP) pollut...,Virulence,2026-07-01,"['XuZhang', 'KeLiu', 'ZhiqiangZhang', 'XinyuHu...",2026.0,['allergic']
2235184,Using new approach methodologies (NAMs) to inv...,10.1038/s41598-026-60082-z,Zinc oxide nanoparticles (ZnONPs) are widely u...,Scientific reports,2026-07-01,"['Yu-YingChen', 'Bour-JrWang', 'Yung-HsuanChen...",2026.0,['allergic']
2235185,Penicillin allergy assessment pathway to impro...,10.3310/BEYF6487,People with penicillin allergy labels receive ...,NaN,2026-01-01,"['Jonathan ATSandoe', 'JennyBoards', 'Christop...",2026.0,['allergic']

In [9]:
data.columns

Index(['title', 'doi', 'abstract', 'journal', 'date', 'authors', 'year',
       'keyword'],
      dtype='str')

In [10]:
data.shape

(2235186, 8)

In [11]:
data.info

<bound method DataFrame.info of                                                      title  \
0                 IV. Prolapsus of the Rectum in Children.
1                                 HEMIANOPSIA IN MIGRAINE.
2        An attempt to estimate fatigue of the cerebral...
3        VII. Report of a Case of Recovery after Abdomi...
4        A further research into fatigue of the central...
...                                                    ...
2235181  Serotonin Degradation and Lipid Metabolism Reg...
2235182  Investigating the Potential Pharmacological Me...
2235183  Bridging environmental pollution and immune dy...
2235184  Using new approach methodologies (NAMs) to inv...
2235185  Penicillin allergy assessment pathway to impro...

                                          doi  \
0            10.1097/00000658-190001000-00028
1                10.1126/science.11.279.713-a
2              10.1113/jphysiol.1901.sp000832
3            10.1097/00000658-190101000-00030
4              10.1113/jphysiol.1902.sp000895
...                                       ...
2235181                     10.1111/all.70399
2235182  10.2174/0113862073449045260321213418
2235183         10.1080/21505594.2026.2690759
2235184            10.1038/s41598-026-60082-z
2235185                      10.3310/BEYF6487

                                                  abstract  \
0                                                      NaN
1                                                      NaN
2                                                      NaN
3                                                      NaN
4                                                      NaN
...                                                    ...
2235181  Cytotoxic type 2 T cells (Tc2) are increasingl...
2235182  Allergic rhinitis (AR) is a common immune diso...
2235183  Parallel increases in microplastic (MP) pollut...
2235184  Zinc oxide nanoparticles (ZnONPs) are widely u...
2235185  People with penicillin allergy labels receive ...

                                                   journal        date  \
0                                        Annals of surgery  1900-03-01
1                                 Science (New York, N.Y.)  1900-05-04
2                                The Journal of physiology  1901-02-28
3                                        Annals of surgery  1901-03-01
4                                The Journal of physiology  1902-03-27
...                                                    ...         ...
2235181                                            Allergy  2026-07-01
2235182  Combinatorial chemistry & high throughput scre...  2026-07-01
2235183                                          Virulence  2026-07-01
2235184                                 Scientific reports  2026-07-01
2235185                                                NaN  2026-01-01

                                                   authors    year  \
0                                           ['C GCumston']  1900.0
1                                           ['J MBaldwin']  1900.0
2                                              ['A GLevy']  1901.0
3                                              ['FMartin']  1901.0
4                                              ['A GLevy']  1902.0
...                                                    ...     ...
2235181  ['Sabrinade Souza Ferreira', 'LisaHolla', 'Sop...  2026.0
2235182  ['ZehuaLin', 'AikebaierTuohuti', 'XiupingYang'...  2026.0
2235183  ['XuZhang', 'KeLiu', 'ZhiqiangZhang', 'XinyuHu...  2026.0
2235184  ['Yu-YingChen', 'Bour-JrWang', 'Yung-HsuanChen...  2026.0
2235185  ['Jonathan ATSandoe', 'JennyBoards', 'Christop...  2026.0

                 keyword
0        ['hemorrhoids']
1           ['migraine']
2            ['fatigue']
3        ['hemorrhoids']
4            ['fatigue']
...                  ...
2235181     ['allergic']
2235182     ['allergic']
2235183     ['allergic']
2235184     ['allergic']
2235185     ['allergic']

[2235186 rows x 8 columns]>